### ISSUE TITLE
Any plans to maintain elixir-build?

### ISSUE THREAD

**Issue by rcoedo** [exenv/exenv#1]
I'm making a pull request to move [anyenv](https://github.com/riywo/anyenv) from mururu's exenv to this exenv, but we have the same problem with elixir-build.

Any plans to take over the project?

thanks!

**Comment by qw3r** [comment]
Hi Roman,

thanks for using my fork in your project!

Regarding the elixir-build, I haven't planned to fork that as well, i mean, as it's working just fine.
I just forked to the exenv 'cause I had some fish-shell related issues with mururu's one.

But if you want to do it, I'll invite you to the exenv "organisation". Are you interested?

**Comment by rcoedo** [comment]
I've checked the repository and there are currently no issues in it. As long as it is maintained, I have no problem with leaving it like this.

If issues start to pile up it would be fine to fork it as well. I can help with it if needed.

Thanks!

**Comment by qw3r** [comment]
Okay, so we are on the same page! :)
